/**
 * Midi 的像素资产 —— 逐字取自 design/midi-prototype.html 的 PAL / CAT / LAMP / KEYBOARD。
 *
 * 为什么整块搬而不是重画：原型是这批帧唯一的设计真源（designer 是在像素网格上直接画的，
 * 没有 PNG 素材）。重画一遍就等于有了第二份，两份迟早分家，而「猫长什么样」这种事
 * 没有任何断言拦得住漂移。改帧请改原型，再把这里同步过来。
 *
 * 颜色分两类：
 *   · 猫的 5 色写在这里（简报 §4：猫的米色是**分类色**，不属于 tokens 的语义色，
 *     所以允许字面量，和身份色、热力图绿一样不参与 accent 计数）；
 *   · 场景的 4 个字符（k / K / L / z）**不在这里**给色值，它们由渲染层从 tokens 取
 *     （--hairline / --canvas / --ink / --mute），见 app.ts 的 midiPalette()。
 *     桌子和灯是这块屏的一部分，得跟着整屏的中性阶走，不能自带一套灰。
 */

/** 一帧 = 每行一个字符串，'.' 是透明。行长不要求等长（原型里也不等长）。 */
export type Frame = string[]

export type FrameName = 'idle' | 'typeL' | 'typeR' | 'look' | 'blink' | 'night' | 'sleep'

const F = (s: string): Frame => s.trim().split('\n').map(l => l.trim())

/** 猫的 5 色：中银灰底 / 近黑虎斑与腿环胸带 / 白（嘴、胸、袜）/ 黄绿眼 / 砖粉鼻与耳内。照用户家那只美短银虎斑「壮汉昕晨」画的：
 *  同一物体只允许三阶明度，色相不做冷暖偏移。 */
export const CAT_PAL: Record<string, string> = {
  o: '#b5b7bb', d: '#25262b', h: '#eeeeeb', e: '#a3c257', p: '#c07b7b'
}

/** 16×14 格。sleep 是趴下的姿势，所以整体下移了 3 行。 */
export const CAT: Record<FrameName, Frame> = {
  idle: F(`
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .oooooooooooo...
    .ooeoooooooeo...
    .odoooooooodo...
    .oohhhphhhooo...
    ..ohhhhhhhho....
    ...ohhhhhho.....
    ..ddodhhdodd....
    .odoodhhdoodo...
    .oo.dddddd.oo...
    .dd.oooooo.dd...
    .hh........hh...`),
  typeL: F(`
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .oooooooooooo...
    .ooeoooooooeo...
    .odoooooooodo...
    .oohhhphhhooo...
    ..ohhhhhhhho....
    ...ohhhhhho.....
    ..ddodhhdodd....
    .odoodhhdoodo...
    .oo.dddddd.oo...
    .dd.oooooo.dd...
    ...........hh...`),
  typeR: F(`
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .oooooooooooo...
    .ooeoooooooeo...
    .odoooooooodo...
    .oohhhphhhooo...
    ..ohhhhhhhho....
    ...ohhhhhho.....
    ..ddodhhdodd....
    .odoodhhdoodo...
    .oo.dddddd.oo...
    .dd.oooooo.dd...
    .hh.............`),
  look: F(`
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .oodooooooodoo..
    .ooeoooooooeo...
    .odoooooooodo...
    .oohhhphhhooo...
    ..ohhhhhhhho....
    ...ohhhhhho.....
    ..ddodhhdodd....
    .odoodhhdoodo...
    .oo.dddddd.oo...
    .dd.oooooo.dd...
    .hh........hh...`),
  blink: F(`
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .oooooooooooo...
    .oodoooooooodo..
    .odoooooooodo...
    .oohhhphhhooo...
    ..ohhhhhhhho....
    ...ohhhhhho.....
    ..ddodhhdodd....
    .odoodhhdoodo...
    .oo.dddddd.oo...
    .dd.oooooo.dd...
    .hh........hh...`),
  night: F(`
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .oooooooooooo...
    .oodeoooooodeo..
    .odoooooooodo...
    .oohhhphhhooo...
    ..ohhhhhhhho....
    ...ohhhhhho.....
    ..ddodhhdodd....
    .odoodhhdoodo...
    .oo.dddddd.oo...
    .dd.oooooo.dd...
    .hh........hh...`),
  sleep: F(`
    ................
    ................
    ................
    ..o........o....
    .opo......opo...
    .oodoodoodooo...
    .odoooooooodo...
    .oodoooooooodo..
    .oooooooooooo...
    .oohhhphhhooo...
    .oooooooooooooo.
    oddoodoodoodddo.
    ooooooooooooooo.
    .hhoooooooooohh.`)
}

/** 桌上的灯，8×14 格。z = 灯杆与灯罩边（--mute），L = 灯罩里亮着的那片（--ink）。 */
export const LAMP: Frame = F(`
  ..zzzz..
  .zLLLLz.
  .zLLLLz.
  ..zzzz..
  ....z...
  ....z...
  ....z...
  ....z...
  ....z...
  ....z...
  ....z...
  ....z...
  ...zzz..
  ..zzzzz.`)

/** 键盘，20×4 格。k = 键盘本体（--hairline），K = 键帽（--canvas，比本体暗一档）。 */
export const KEYBOARD: Frame = F(`
  kkkkkkkkkkkkkkkkkkkk
  kKkKkKkKkKkKkKkKkKkk
  kkkkkkkkkkkkkkkkkkkk
  kKKKKKKKKKKKKKKKKKkk`)

/** 猫从第 11 行起是爪子，要补画在键盘之上（它坐在桌后，爪子在键上） */
export const CAT_PAW_ROW = 11
